# Generated by Django 5.2.1 on 2025-07-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialacceso',
            name='tipo_evento',
        ),
        migrations.AddField(
            model_name='historialacceso',
            name='accion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialacceso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='core.usuario'),
        ),
    ]
